// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_1nZw3HsUiVxQDCP6MDFsrMaAson0Al8',
    appId: '1:829319450474:web:f2fd584899852fce269f13',
    messagingSenderId: '829319450474',
    projectId: 'productauthenticity-4ac6b',
    authDomain: 'productauthenticity-4ac6b.firebaseapp.com',
    storageBucket: 'productauthenticity-4ac6b.appspot.com',
    measurementId: 'G-4D0P8GWBLR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP9tiQGqaedPpqeyROhKxc8tQTx8ULUfQ',
    appId: '1:829319450474:android:5bcde6b2e9056c83269f13',
    messagingSenderId: '829319450474',
    projectId: 'productauthenticity-4ac6b',
    storageBucket: 'productauthenticity-4ac6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT8kSZD37kG5vCePqKm8OAjjn4hm0A80Y',
    appId: '1:829319450474:ios:b5b9c3dc6f5df2bf269f13',
    messagingSenderId: '829319450474',
    projectId: 'productauthenticity-4ac6b',
    storageBucket: 'productauthenticity-4ac6b.appspot.com',
    iosBundleId: 'com.example.productAuthenticityFss',
  );
}
