// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADobz4bCfT9JUTKw5iCTMyS84vZLnBTy8',
    appId: '1:701556771654:web:4fb0e45a842e233d897347',
    messagingSenderId: '701556771654',
    projectId: 'productauth-67c25',
    authDomain: 'productauth-67c25.firebaseapp.com',
    storageBucket: 'productauth-67c25.appspot.com',
    measurementId: 'G-JBCPCN73RL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3DRzOxfdqZNu0iMwLd9cOd8fRXEtfO2I',
    appId: '1:701556771654:android:c25e38cb0d4e8ba9897347',
    messagingSenderId: '701556771654',
    projectId: 'productauth-67c25',
    storageBucket: 'productauth-67c25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGAWkWiAZtHYbO2ChOwOChAI2lKJTSbMA',
    appId: '1:701556771654:ios:0c270e775ae191c9897347',
    messagingSenderId: '701556771654',
    projectId: 'productauth-67c25',
    storageBucket: 'productauth-67c25.appspot.com',
    iosBundleId: 'com.example.productAuthenticityFss',
  );

}